all: os_lec3_ex2 test1 test2 test3 test4 test5

os_lec3_ex2: os_lec3_ex2.c
	gcc -o os_lec3_ex2 os_lec3_ex2.c 

test1: test1.c
	gcc -o test1 test1.c

test2: test2.c
	gcc -o test2 test2.c -lm

test3: test3.c
	gcc -o test3 test3.c

test4: test4.c
	gcc -o test4 test4.c

test5: test5.c
	gcc -o test5 test5.c

